// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: leaderboards.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLeaderboard = `-- name: CreateLeaderboard :one
INSERT INTO "leaderboards" ("game_id", "name", "description", "start_at", "end_at", "aggregation_mode", "data_type", "ordering")
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING "id"
`

type CreateLeaderboardParams struct {
	GameID          string
	Name            string
	Description     string
	StartAt         pgtype.Timestamptz
	EndAt           pgtype.Timestamptz
	AggregationMode string
	DataType        string
	Ordering        string
}

func (q *Queries) CreateLeaderboard(ctx context.Context, arg CreateLeaderboardParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createLeaderboard,
		arg.GameID,
		arg.Name,
		arg.Description,
		arg.StartAt,
		arg.EndAt,
		arg.AggregationMode,
		arg.DataType,
		arg.Ordering,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
