// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Quest struct {
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	ID          uuid.UUID
	GameID      string
	Name        string
	Description string
}

type Task struct {
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	QuestID     uuid.UUID
	ID          uuid.UUID
	Name        string
	Description string
	DependsOn   pgtype.UUID
	Rule        string
}
