// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PlayerQuest struct {
	StartedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	ID          uuid.UUID
	PlayerID    string
	QuestID     uuid.UUID
	CompletedAt pgtype.Timestamptz
}

type PlayerQuestTask struct {
	StartedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
	ID            uuid.UUID
	PlayerID      string
	PlayerQuestID uuid.UUID
	TaskID        uuid.UUID
	CompletedAt   pgtype.Timestamptz
}

type Quest struct {
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
	ID          uuid.UUID
	GameID      string
	Name        string
	Description string
}

type Task struct {
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	DeletedAt             pgtype.Timestamptz
	QuestID               uuid.UUID
	ID                    uuid.UUID
	Name                  string
	Description           string
	RequiredForCompletion bool
	Rule                  string
}

type TasksDependency struct {
	ThisTask      uuid.UUID
	DependsOnTask uuid.UUID
}

type TasksWithItsDependency struct {
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	DeletedAt             pgtype.Timestamptz
	QuestID               uuid.UUID
	ID                    uuid.UUID
	Name                  string
	Description           string
	RequiredForCompletion bool
	Rule                  string
	DependsOn             []uuid.UUID
}
