// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: task.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO "tasks" ("quest_id", "name", "description", "depends_on", "rule")
VALUES ($1, $2, $3, $4, $5)
RETURNING created_at, updated_at, deleted_at, quest_id, id, name, description, depends_on, rule
`

type CreateTaskParams struct {
	QuestID     uuid.UUID
	Name        string
	Description string
	DependsOn   pgtype.UUID
	Rule        string
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.QuestID,
		arg.Name,
		arg.Description,
		arg.DependsOn,
		arg.Rule,
	)
	var i Task
	err := row.Scan(
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.QuestID,
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DependsOn,
		&i.Rule,
	)
	return i, err
}
