version: '3.8'

services:
  # Auth
  keycloack:
    image: quay.io/keycloak/keycloak:latest
    command: ['start-dev']
    ports:
      - 3000:8080
    environment:
      KEYCLOAK_ADMIN: gameblitz
      KEYCLOAK_ADMIN_PASSWORD: gameblitz

  # Databases
  postgres:
    image: postgres:16-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: gameblitz
      POSTGRES_USER: gameblitz
      POSTGRES_PASSWORD: gameblitz
  mongo:
    image: mongo:7
    ports:
      - 27017:27017
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  # Cache
  memcached:
    image: memcached:1-alpine
    ports:
      - 11211:11211

  # Events
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: gameblitz
      RABBITMQ_DEFAULT_PASS: gameblitz
      RABBITMQ_DEFAULT_VHOST: gameblitz
