// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/leaderboards": {
            "post": {
                "description": "Create a leaderboard",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create Leaderboard",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID responsible for the leaderboard",
                        "name": "X-Game-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "New leaderboard config data",
                        "name": "NewLeaderboardData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rest.CreateLeaderboardReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/rest.Leaderboard"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/leaderboards/{leaderboardId}": {
            "get": {
                "description": "Return a leaderboard by id and game id",
                "produces": [
                    "application/json"
                ],
                "summary": "Get Leaderboard",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID responsible for the leaderboard",
                        "name": "X-Game-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Leaderboard ID",
                        "name": "leaderboardId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/rest.Leaderboard"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete a leaderboard by id and game id",
                "summary": "Delete Leaderboard",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID responsible for the leaderboard",
                        "name": "X-Game-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Leaderboard ID",
                        "name": "leaderboardId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/leaderboards/{leaderboardId}/ranking": {
            "get": {
                "description": "Get the leaderboard ranking paginated",
                "produces": [
                    "application/json"
                ],
                "summary": "Leaderboard Ranking",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID responsible for the leaderboard",
                        "name": "X-Game-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Leaderboard ID",
                        "name": "leaderboardId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 0,
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "maximum": 500,
                        "type": "integer",
                        "default": 10,
                        "description": "Number of rankings per page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/rest.Rank"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/leaderboards/{leaderboardId}/ranking/{playerId}": {
            "post": {
                "description": "Set or update a player's rank on the leaderboard",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Upsert Player Rank",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID responsible for the leaderboard",
                        "name": "X-Game-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Leaderboard ID",
                        "name": "leaderboardId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Player ID",
                        "name": "playerId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Values to update the player rank",
                        "name": "UpsertPlayerRankData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rest.UpsertPlayerRankReq"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/quests": {
            "post": {
                "description": "Create a quest and its tasks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Create Quest",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Game ID responsible for the leaderboard",
                        "name": "X-Game-ID",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "New quest config data",
                        "name": "NewQuestData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/rest.CreateQuestReq"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/rest.Quest"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "422": {
                        "description": "Unprocessable Entity",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/rest.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "rest.CreateLeaderboardReq": {
            "type": "object",
            "properties": {
                "aggregationMode": {
                    "description": "Data aggregation mode",
                    "type": "string",
                    "enum": [
                        "INC",
                        "MAX",
                        "MIN"
                    ]
                },
                "description": {
                    "description": "Leaderboard's description",
                    "type": "string"
                },
                "endAt": {
                    "description": "Time that the leaderboard will be closed for new updates",
                    "type": "string"
                },
                "name": {
                    "description": "Leaderboard's name",
                    "type": "string"
                },
                "ordering": {
                    "description": "Leaderboard ranking order",
                    "type": "string",
                    "enum": [
                        "ASC",
                        "DESC"
                    ]
                },
                "startAt": {
                    "description": "Time that the leaderboard should start working",
                    "type": "string"
                }
            }
        },
        "rest.CreateQuestReq": {
            "type": "object",
            "properties": {
                "description": {
                    "description": "Quest details",
                    "type": "string"
                },
                "name": {
                    "description": "Quest name",
                    "type": "string"
                },
                "tasks": {
                    "description": "Quest task list",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "dependsOn": {
                                "description": "Array index of the task that needs to be completed before this one can be started",
                                "type": "integer"
                            },
                            "description": {
                                "description": "Task details",
                                "type": "string"
                            },
                            "name": {
                                "description": "Task name",
                                "type": "string"
                            },
                            "rule": {
                                "description": "Task completion logic as JsonLogic. See https://jsonlogic.com/",
                                "type": "string"
                            }
                        }
                    }
                },
                "tasksValidators": {
                    "description": "Quest task list success validation data",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "rest.ErrorResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "Error unique code",
                    "type": "string"
                },
                "details": {
                    "description": "Details about the source of the error",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "message": {
                    "description": "Error message",
                    "type": "string"
                }
            }
        },
        "rest.Leaderboard": {
            "type": "object",
            "properties": {
                "aggregationMode": {
                    "description": "Data aggregation mode",
                    "type": "string",
                    "enum": [
                        "INC",
                        "MAX",
                        "MIN"
                    ]
                },
                "createdAt": {
                    "description": "Time that the leaderboard was created",
                    "type": "string"
                },
                "description": {
                    "description": "Leaderboard's description",
                    "type": "string"
                },
                "endAt": {
                    "description": "Time that the leaderboard will be closed for new updates",
                    "type": "string"
                },
                "gameId": {
                    "description": "The ID from the game that is responsible for the leaderboard",
                    "type": "string"
                },
                "id": {
                    "description": "Leaderboard's ID",
                    "type": "string"
                },
                "name": {
                    "description": "Leaderboard's name",
                    "type": "string"
                },
                "ordering": {
                    "description": "Leaderboard ranking order",
                    "type": "string",
                    "enum": [
                        "ASC",
                        "DESC"
                    ]
                },
                "startAt": {
                    "description": "Time that the leaderboard should start working",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "Last time that the leaderboard info was updated",
                    "type": "string"
                }
            }
        },
        "rest.Quest": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "Time that the quest was created",
                    "type": "string"
                },
                "description": {
                    "description": "Quest details",
                    "type": "string"
                },
                "gameId": {
                    "description": "ID of the game responsible for the quest",
                    "type": "string"
                },
                "id": {
                    "description": "Quest ID",
                    "type": "string"
                },
                "name": {
                    "description": "Quest name",
                    "type": "string"
                },
                "tasks": {
                    "description": "Quest task list",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/rest.Task"
                    }
                },
                "updatedAt": {
                    "description": "Last time that the quest was updated",
                    "type": "string"
                }
            }
        },
        "rest.Rank": {
            "type": "object",
            "properties": {
                "playerId": {
                    "description": "Player's ID",
                    "type": "string"
                },
                "position": {
                    "description": "Player ranking position",
                    "type": "integer"
                },
                "value": {
                    "description": "Player rank value",
                    "type": "number"
                }
            }
        },
        "rest.Task": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "description": "Time that the task was created",
                    "type": "string"
                },
                "dependsOn": {
                    "description": "ID of the task that needs to be completed before this one can be started",
                    "type": "string"
                },
                "description": {
                    "description": "Task details",
                    "type": "string"
                },
                "id": {
                    "description": "Task ID",
                    "type": "string"
                },
                "name": {
                    "description": "Task name",
                    "type": "string"
                },
                "rule": {
                    "description": "Task completion logic as JsonLogic. See https://jsonlogic.com/",
                    "type": "string"
                },
                "updatedAt": {
                    "description": "Last time that the task was updated",
                    "type": "string"
                }
            }
        },
        "rest.UpsertPlayerRankReq": {
            "type": "object",
            "properties": {
                "value": {
                    "description": "Value that will be used to update the player's rank",
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Metagaming API",
	Description:      "An API to handle basic gaming features like Quests and Leaderboards",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
